[package]
name = "omendb"
version = "0.1.0"
edition = "2021"
authors = ["OmenDB Inc."]
description = "World's first database using only learned indexes"
license = "Proprietary"

[dependencies]
# Core essentials only for now
anyhow = "1.0"
thiserror = "1.0"

# Math for learned indexes
ndarray = "0.15"

# Storage (simplified for now)
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# Performance
rayon = "1.8"
parking_lot = "0.12"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.bench]
inherits = "release"

# Benchmarks to be added later