[workspace]
authors = ["Nick Russo <nijaru7@gmail.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "omenDB"
platforms = ["osx-arm64", "linux-64"]
version = "0.0.1"

[dependencies]
modular = "==25.4.0"
python = ">=3.11,<3.14"
numpy = ">=1.26.4,<2"

[tasks]
clean = { cmd = "rm -rf test_data/*.omen build/ dist/ *.mojopkg *.profdata *.svg || true", description = "Clean build artifacts and test databases" }
test = { cmd = "pixi run mojo -I omendb test/", description = "Run test suite" }
format = { cmd = "mojo format omendb/ test/ examples/", description = "Format Mojo code" }
build = { cmd = "mojo build omendb/native.mojo -o python/omendb/native.so --emit shared-lib -I omendb", description = "Build native module" }