apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: omendb-server
  labels:
    app: omendb-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omendb-server
  
  minReplicas: 3
  maxReplicas: 50
  
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory-based scaling  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics from Prometheus
  - type: Pods
    pods:
      metric:
        name: omendb_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"  # Scale up when >1000 RPS per pod
  
  - type: Pods
    pods:
      metric:
        name: omendb_query_latency_p99
      target:
        type: AverageValue
        averageValue: "10m"   # Scale up when P99 latency >10ms
  
  # Scale-down behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10      # Scale down max 10% of pods at once
        periodSeconds: 60
      - type: Pods
        value: 2       # Or max 2 pods at once
        periodSeconds: 60
      selectPolicy: Min  # Use the more conservative policy
    
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      policies:
      - type: Percent
        value: 50      # Scale up max 50% at once for quick response
        periodSeconds: 60
      - type: Pods
        value: 5       # Or max 5 pods at once
        periodSeconds: 60
      selectPolicy: Max  # Use the more aggressive policy

---
# Vertical Pod Autoscaler for resource optimization
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: omendb-server-vpa
  labels:
    app: omendb-server
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omendb-server
  
  updatePolicy:
    updateMode: "Auto"  # Automatically apply recommendations
  
  resourcePolicy:
    containerPolicies:
    - containerName: omendb-server
      minAllowed:
        cpu: 500m
        memory: 1Gi
      maxAllowed:
        cpu: 8
        memory: 16Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits