apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: omendb-server
  annotations:
    config.kubernetes.io/local-config: "true"

# Namespace for all resources
namespace: omendb-system

# Common labels applied to all resources
commonLabels:
  app: omendb-server
  version: v0.1.0
  component: database

# Resources to include
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- rbac.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml
- monitoring.yaml

# Namespace creation
- namespace.yaml

# Images to use
images:
- name: omendb/server
  newTag: v0.1.0

# ConfigMap generator for additional configs
configMapGenerator:
- name: omendb-env-config
  literals:
  - RUST_LOG=info,omendb_server=debug
  - RUST_BACKTRACE=1
  - OMENDB_ENVIRONMENT=production

# Secret generator for additional secrets  
secretGenerator:
- name: omendb-additional-secrets
  literals:
  - monitoring-token=changeme

# Patches for different environments
patchesStrategicMerge:
- patches/production.yaml

# JSON patches for specific modifications
patches:
- target:
    kind: Deployment
    name: omendb-server
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

# Replacements for templating
replacements:
- source:
    kind: ConfigMap
    name: omendb-config
    fieldPath: data.cluster-name
  targets:
  - select:
      kind: Deployment
      name: omendb-server
    fieldPaths:
    - spec.template.spec.containers.[name=omendb-server].env.[name=CLUSTER_NAME].value