apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: omendb-production

namespace: omendb-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - pvc-patch.yaml

images:
  - name: omendb
    newTag: v0.1.0

replicas:
  - name: omendb
    count: 3