apiVersion: v1
kind: ConfigMap
metadata:
  name: omendb-config
data:
  auth_disabled: "true"
  log_level: "debug"
  worker_threads: "2"
  max_connections: "50"

  omendb_toml: |
    # OmenDB Development Configuration

    [database]
    name = "omendb_dev"
    data_dir = "/var/lib/omendb/data"
    max_memory_mb = 512
    expected_size = 1000000

    [storage]
    enable_compression = false
    batch_size = 10000
    sync_interval_ms = 10000

    [index]
    model_type = "recursive"
    max_error = 100
    retrain_threshold = 50000

    [wal]
    enabled = true
    sync_on_write = false
    max_file_size_mb = 50
    rotation_interval_hours = 12

    [http]
    host = "0.0.0.0"
    port = 3000
    request_timeout_ms = 60000
    max_concurrent_requests = 100

    [security]
    auth_enabled = false
    session_timeout_seconds = 7200
    tls_enabled = false

    [monitoring]
    prometheus_enabled = true
    prometheus_port = 9090
    health_check_interval_ms = 5000
    log_level = "debug"
    log_format = "pretty"

    [performance]
    worker_threads = 2
    io_threads = 1
    enable_simd = true
    prefetch_size = 500

    [limits]
    max_connections = 50
    max_query_duration_ms = 120000
    max_insert_batch_size = 5000
    memory_limit_mb = 512