apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: omendb-development

namespace: omendb-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: omendb
    newTag: dev