# OmenDB Server Configuration

[server]
http_port = 8080
grpc_port = 9090
worker_threads = 4
max_connections = 1000
request_timeout = 30  # seconds
keep_alive_timeout = 60  # seconds
max_request_size = 10485760  # 10MB

[engine]
dimension = 128
pool_size = 10
idle_timeout = 300  # seconds
max_vectors_per_engine = 1000000
enable_tiered_storage = false  # Disable for initial testing

[auth]
enabled = false  # Disable all authentication for testing
jwt_secret = "test-secret-key-for-development"
jwt_expiration = 86400  # 24 hours in seconds
enable_api_keys = false  # Disable for initial testing

[auth.rate_limit]
requests_per_minute = 10000  # High limit for testing
burst_capacity = 1000

[storage]
data_dir = "./data"
enable_hot_tier = true
hot_tier_memory_mb = 1024
enable_warm_tier = false  # Disable for initial testing
warm_tier_path = "./data/warm"
enable_cold_tier = false
cold_tier_path = "./data/cold"

[metrics]
enabled = true
port = 9091
collection_interval = 60  # seconds
enable_engine_metrics = true