apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omendb-data
  labels:
    app: omendb
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd  # Adjust based on your storage class