apiVersion: v1
kind: ServiceAccount
metadata:
  name: omendb
  labels:
    app: omendb
    component: database

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: omendb
  labels:
    app: omendb
    component: database
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omendb
  labels:
    app: omendb
    component: database
subjects:
- kind: ServiceAccount
  name: omendb
  namespace: default
roleRef:
  kind: Role
  name: omendb
  apiGroup: rbac.authorization.k8s.io