apiVersion: v1
kind: Service
metadata:
  name: omendb
  labels:
    app: omendb
    component: database
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: omendb

---
apiVersion: v1
kind: Service
metadata:
  name: omendb-headless
  labels:
    app: omendb
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: omendb