apiVersion: v1
kind: ConfigMap
metadata:
  name: omendb-config
data:
  auth_disabled: "false"
  log_level: "info"
  worker_threads: "6"
  max_connections: "200"

  omendb_toml: |
    # OmenDB Staging Configuration

    [database]
    name = "omendb_staging"
    data_dir = "/var/lib/omendb/data"
    max_memory_mb = 2048
    expected_size = 5000000

    [storage]
    enable_compression = true
    batch_size = 30000
    sync_interval_ms = 7500

    [index]
    model_type = "recursive"
    max_error = 100
    retrain_threshold = 75000

    [wal]
    enabled = true
    sync_on_write = true
    max_file_size_mb = 75
    rotation_interval_hours = 18

    [http]
    host = "0.0.0.0"
    port = 3000
    request_timeout_ms = 45000
    max_concurrent_requests = 500

    [security]
    auth_enabled = true
    session_timeout_seconds = 3600
    tls_enabled = true

    [monitoring]
    prometheus_enabled = true
    prometheus_port = 9090
    health_check_interval_ms = 7500
    log_level = "info"
    log_format = "json"

    [performance]
    worker_threads = 6
    io_threads = 2
    enable_simd = true
    prefetch_size = 750

    [limits]
    max_connections = 200
    max_query_duration_ms = 90000
    max_insert_batch_size = 7500
    memory_limit_mb = 2048