apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: omendb-staging

namespace: omendb-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: omendb
    newTag: staging

replicas:
  - name: omendb
    count: 2