[package]
name = "omendb"
version = "0.1.0"
edition = "2021"
authors = ["OmenDB Inc."]
description = "World's first database using only learned indexes"
license = "Proprietary"

[dependencies]
# Just the essentials for now

[profile.release]
lto = true
codegen-units = 1
opt-level = 3