[package]
name = "omendb"
version = "0.1.0"
edition = "2021"
authors = ["OmenDB Inc."]
description = "World's first database using only learned indexes"
license = "Proprietary"
repository = "https://github.com/omendb/core"

[dependencies]
# Web framework for API
axum = "0.7"
tokio = { version = "1.35", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "compression"] }

# PostgreSQL wire protocol
pgwire = "0.20"
async-trait = "0.1"

# Storage and serialization
arrow = "50.0"
parquet = "50.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Math and ML for learned indexes
ndarray = "0.15"
linfa = "0.7"
linfa-linear = "0.7"

# Database essentials
bytes = "1.5"
byteorder = "1.5"
crc32fast = "1.3"

# Logging and errors
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"

# Performance
rayon = "1.8"
crossbeam = "0.8"
parking_lot = "0.12"
dashmap = "5.5"

# Testing and benchmarking
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"

[dev-dependencies]
rand = "0.8"
tempfile = "3.8"
pretty_assertions = "1.4"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.bench]
inherits = "release"

# Benchmarks will be added later
# [[bench]]
# name = "learned_vs_btree"
# harness = false