apiVersion: v1
kind: ConfigMap
metadata:
  name: omendb-config
data:
  auth_disabled: "false"
  log_level: "warn"
  worker_threads: "8"
  max_connections: "1000"
  enable_metrics: "true"
  metrics_port: "9090"

  omendb_toml: |
    # OmenDB Production Configuration

    [database]
    name = "omendb_production"
    data_dir = "/var/lib/omendb/data"
    max_memory_mb = 3072
    expected_size = 50000000

    [storage]
    enable_compression = true
    batch_size = 100000
    sync_interval_ms = 5000

    [index]
    model_type = "recursive"
    max_error = 50
    retrain_threshold = 500000

    [wal]
    enabled = true
    sync_on_write = true
    max_file_size_mb = 200
    rotation_interval_hours = 24

    [http]
    host = "0.0.0.0"
    port = 3000
    request_timeout_ms = 30000
    max_concurrent_requests = 2000

    [security]
    auth_enabled = true
    session_timeout_seconds = 1800
    tls_enabled = true

    [monitoring]
    prometheus_enabled = true
    prometheus_port = 9090
    health_check_interval_ms = 15000
    log_level = "warn"
    log_format = "json"

    [performance]
    worker_threads = 8
    io_threads = 4
    enable_simd = true
    prefetch_size = 2000

    [limits]
    max_connections = 1000
    max_query_duration_ms = 30000
    max_insert_batch_size = 50000
    memory_limit_mb = 3072