apiVersion: v1
kind: ConfigMap
metadata:
  name: omendb-config
  labels:
    app: omendb
    component: database
data:
  auth_disabled: "false"
  session_timeout: "3600"
  worker_threads: "4"
  max_connections: "100"
  log_level: "info"
  enable_metrics: "true"
  metrics_port: "9090"

  # OmenDB configuration file
  omendb_toml: |
    # OmenDB Kubernetes Configuration

    [database]
    name = "omendb_k8s"
    data_dir = "/var/lib/omendb/data"
    max_memory_mb = 1536
    expected_size = 10000000

    [storage]
    enable_compression = true
    batch_size = 50000
    sync_interval_ms = 5000

    [index]
    model_type = "recursive"
    max_error = 100
    retrain_threshold = 100000

    [wal]
    enabled = true
    sync_on_write = true
    max_file_size_mb = 100
    rotation_interval_hours = 24

    [http]
    host = "0.0.0.0"
    port = 3000
    request_timeout_ms = 30000
    max_concurrent_requests = 1000

    [security]
    auth_enabled = true
    session_timeout_seconds = 3600
    tls_enabled = false

    [monitoring]
    prometheus_enabled = true
    prometheus_port = 9090
    health_check_interval_ms = 10000
    log_level = "info"
    log_format = "json"

    [performance]
    worker_threads = 4
    io_threads = 2
    enable_simd = true
    prefetch_size = 1000

    [limits]
    max_connections = 100
    max_query_duration_ms = 60000
    max_insert_batch_size = 10000
    memory_limit_mb = 1536