apiVersion: apps/v1
kind: Deployment
metadata:
  name: omendb
  labels:
    app: omendb
    component: database
    version: v0.1.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: omendb
  template:
    metadata:
      labels:
        app: omendb
        component: database
        version: v0.1.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: omendb
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: omendb
        image: omendb:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: RUST_LOG
          value: info
        - name: OMENDB_DATA_DIR
          value: /var/lib/omendb/data
        - name: OMENDB_LOG_DIR
          value: /var/log/omendb
        - name: OMENDB_HTTP_PORT
          value: "3000"
        - name: OMENDB_AUTH_DISABLED
          valueFrom:
            configMapKeyRef:
              name: omendb-config
              key: auth_disabled
        - name: OMENDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: omendb-secret
              key: admin_user
        - name: OMENDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: omendb-secret
              key: admin_password
        - name: OMENDB_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: omendb-secret
              key: jwt_secret
        - name: OMENDB_SESSION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: omendb-config
              key: session_timeout
        - name: OMENDB_WORKER_THREADS
          valueFrom:
            configMapKeyRef:
              name: omendb-config
              key: worker_threads
        - name: OMENDB_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: omendb-config
              key: max_connections
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/omendb/data
        - name: logs
          mountPath: /var/log/omendb
        - name: config
          mountPath: /etc/omendb
          readOnly: true
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: omendb-data
      - name: logs
        emptyDir:
          sizeLimit: 10Gi
      - name: config
        configMap:
          name: omendb-config
          items:
          - key: omendb_toml
            path: omendb.toml
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "omendb"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - omendb
              topologyKey: kubernetes.io/hostname