apiVersion: v1
kind: ConfigMap
metadata:
  name: omendb-config
  labels:
    app: omendb-server
data:
  config.toml: |
    [server]
    http_port = 8080
    grpc_port = 9090
    worker_threads = 8
    max_connections = 10000
    request_timeout = "30s"
    keep_alive_timeout = "60s"
    max_request_size = 10485760  # 10MB

    [engine]
    dimension = 128
    pool_size = 10
    idle_timeout = "300s"
    max_vectors_per_engine = 1000000
    enable_tiered_storage = true

    [auth]
    jwt_expiration = "24h"
    enable_api_keys = true

    [auth.rate_limit]
    requests_per_minute = 10000
    burst_capacity = 1000

    [storage]
    data_dir = "/app/data"
    enable_hot_tier = true
    hot_tier_memory_mb = 2048
    enable_warm_tier = true
    warm_tier_path = "/app/data/warm"
    enable_cold_tier = true
    cold_tier_path = "s3://omendb-cold-storage"

    [metrics]
    enabled = true
    port = 9091
    collection_interval = "60s"
    enable_engine_metrics = true